<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInit83b5caedaa5c5af51bb267243a971bb6
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('StripeWPFS\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \StripeWPFS\Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        require __DIR__ . '/platform_check.php';

        spl_autoload_register(array('ComposerAutoloaderInit83b5caedaa5c5af51bb267243a971bb6', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \StripeWPFS\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInit83b5caedaa5c5af51bb267243a971bb6', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\StripeWPFS\Composer\Autoload\ComposerStaticInit83b5caedaa5c5af51bb267243a971bb6::getInitializer($loader));

        $loader->setClassMapAuthoritative(true);
        $loader->register(true);

        return $loader;
    }
}
